### ISSUE TITLE
How to compile uTox in VS

### ISSUE THREAD

**Issue by uToxingInTox** [GrayHatter/uTox#151]
I want to compile uTox in Visual Studio. How can I do that? It looks like in windows compiling uTox and debug it is impossible mission. Also, check your 'Tested on Ubuntu 15.10' shell script, it contains errors.

**Comment by GrayHatter** [comment]
I have no idea how to compile µTox in VS, I've looked into it but I gave up pretty quickly.

@linuxraspilxc your ubuntu guide is broken, any thoughts?

**Comment by uToxingInTox** [comment]
how do you debug utox for windows?

**Comment by GrayHatter** [comment]
cygwin 
mingw64
gdb

**Comment by uToxingInTox** [comment]
I think I should try to compile it in VS. What I need for it? Libsodium, toxcore, filter_audio, that's all?
There is no problem with libsodium, I have precompiled binary and headers, but I will have problems with last two

**Comment by GrayHatter** [comment]
you should be able to find all the binaries you need on the build server

**Comment by uToxingInTox** [comment]
I hope.

**Comment by uToxingInTox** [comment]
BTW: what's happened with group calls? Why group call button is not active?

**Comment by GrayHatter** [comment]
When I originally added the new ToxAV API, groupchats weren't supported for
audio. Then once audio was added, I was under the impression that the new
groupchat api would be coming very soon, so I wanted to wait so that I
wouldn't have to fix it again a month later. So right now, they're kinda in
limbo. I did try to reimplement them, but I never got it working
completely, so I moved on because I had to refactor the audio section
anyway.

Right now, It's somewhat in limbo, the code should be easy to reimplement,
but I haven't had the time. And it's triaged kinda low because I'm still
waiting to hear the status on new groupchats.

**Comment by tsudoko** [comment]
Aren't the new groupchats stalled until irungentoo helps with TCP?

**Comment by GrayHatter** [comment]
maybe <question mark>

idealy we'll have new groupchats to demo in time for SCaLE, but no one
knows for sure...

**Comment by linuxraspilxc** [comment]
@uToxingInTox please be more specific on what error you get with my script and at which step

**Comment by uToxingInTox** [comment]
git//github.com/  cd.. also don't use make install, checkinstall is better
