### ISSUE TITLE
dual webcam broken

### ISSUE THREAD

**Issue by sylware** [GrayHatter/uTox#200]
In recent utox, on a system with an integrated webcam and an additional USB webcam, only the integrated webcam can work as it
interferes if we try to configure and use the other USB webcam.

**Comment by GrayHatter** [comment]
Windows?

**Comment by sylware** [comment]
Recent linux x86_64 build

**Comment by miso-** [comment]
Can you try patch for #198 ?

**Comment by sylware** [comment]
:( audio/video issues are for the system of a friend 18000 kilometers away (mine is x86 and mono webcam).

**Comment by GrayHatter** [comment]
can you run

`ls -l /dev/video*`

and 

`lspci`

and

`lsusb`

and confirm that the webcam works elsewhere?

**Comment by sylware** [comment]
Both webcams work.

My friend si not currently at her place with the dual webcam computer. Will
make her update utox to latest version, re-test and if required, give you the
info you want once she's back. Stay tuned.

-- 
Sylvain

**Comment by miso-** [comment]
I am not at the box right now, but it should be reproducible with single cam like this:

mknod /dev/video1 c $(stat -c "%t %T" /dev/video0) # copy video0 to video1
rm /dev/video0 # delete video0
mknod /dev/video0 c $(stat -c "%t %T" /dev/null) # replace video0 with null

you can use strace to verify that /dev/video1 newer gets opened, thats because there is quite obvious error in the code...

**Comment by sylware** [comment]
seems fixed in recent µtox
