### ISSUE TITLE
Updating to 0.8.1 causes broken message windows on first run

### ISSUE THREAD

**Issue by flussence** [GrayHatter/uTox#310]
I just updated from 08935b2 (0.7.1) to e7949ca (current HEAD/0.8.1) and a bunch of things started behaving oddly:

* Message window loaded previous logs correctly but scrolling was messed up: scroll speed was far too slow, scrollbar handle was tiny.
* The message window didn't update to show any sent or received messages, but I still saw typing notifications at the bottom. Switching to/from the config tab and changing things in there at random didn't cause it to redraw with new messages.

After restarting the program everything seems fine, all the missing messages are there too. Not sure if this is even reproducible, but I'll report it just in case someone else encounters the same problem.

**Comment by GrayHatter** [comment]
@flussence that's expected.

 I'll leave this open until v0.9, but when upgrading to v0.8, you're also upgrading to the new messages storage format. The way I chose to do it causes this UI glitch. I didn't think anyone would notice because I hadn't considered the scrolling speed change.

If you or anyone is really throw off by this, I can have utox auto restart after updating the messages. But that's a bit hacky.

**Comment by GrayHatter** [comment]
I changed a bit more, this shouldn't even be an issue now
