### ISSUE TITLE
eye-tearing antialiased font

### ISSUE THREAD

**Issue by FuckYouCannonFodderLovers** [GrayHatter/uTox#311]
Needed simple font <u>and</u> simple rendering, without antialiasing. Or any possibility to customize font, with also simple rendering.

In Ubuntu it is possible to disable this harmful thing system-wide, but corresponding Windows XP settings are not taken into account by uTox.

![eye-tearing_anitaliasing](https://cloud.githubusercontent.com/assets/14297515/15039386/1a0e0a9e-12c6-11e6-9ccb-33c8d5fba0a4.png)

Details:
http://annystudio.com/misc/anti-aliased-fonts-hurt/

**Comment by utoxxer** [comment]
Eye-tearing is a bit over-dramatic don't you think? Doesn't bother me at all. Sounds like a case of an impressionable person reading an article that convinced them they are suffering.

**Comment by GrayHatter** [comment]
I'm with @utoxxer on this one. If you can use anti-aliased font, and choose not to. You're an idiot. The person writing that article has no reason or evidence to back up ANYTHING about it being bad for your eyes. (Apart from the problem of staring into a bright light; use the dark on zenburn theme in uTox!) 

The reasoning behind disabling antialias fonts used to be relevant years ago, when the resolution on a screen was low enough that the text would look blurry because the individual pixels were huge. Now, on most screen they're too small to be seen without magnification of some kind. There is an argument to be made for forcing the eye to refocus onto blurry text (again not relevant with the current size of pixels) But it's instantly negated by ANY straight line.

But, that said... far be it from me to force you to not suffer "fixed" in 854892cacda18fb8fc85944916058c69a7a2bf43 to use the system's default setting.

**Comment by FuckYouCannonFodderLovers** [comment]
So those who is able to consume fast-food - mixture of sh*t and chemical agents, and don't do it, are also idiots? Or idiots - those who lust for novelty, bells and whistlers,

[I had one stupid classmate, who set on 14-inch CRT display 1024*768@60. Not only picture was over-blurred; also flickering was awful. On my display at the same time - Sony 15-inch, i used mainly 800*600@100. While 1024*768 was not so awful like on my classmate's display, 85 Hz was noticeable flickering, that's why i used it only several hours per year. And yes, i can detect between 120 Hz and 100 Hz on CRT display. And... same about sound... i can detect between 16/44,1 and 24/96, and usage of same recording is not necessary. And you don't need super-eye or super-ear for provided examples. You just needed to be serious, not stupid mass consumer.]

No matter of current size of pixels. Blur is **easily** noticeable even on tablet PC screen with 2048*1536, usual book-sized.

Article i found only about 1-2 years ago, while started to disabling of anti-aliasing from 2004 year, from my first LCD display (17 inches).

For link to issue (which is named wrongly) - thanks. For own build i will change font from anti-nature "Deja-vu Sans" to some human, like "Arial", and font settings.
