### ISSUE TITLE
100% cpu load on video call.

### ISSUE THREAD

**Issue by vasisualiy** [GrayHatter/uTox#67]
If I make a call, the utox utilizes 100% cpu. Is it normal behaviour? (Athlon 3500+)

**Comment by cebe** [comment]
no, it is not normal, could you give more information on the version your are using and your system/OS.

**Comment by GrayHatter** [comment]
And where your got you version of uTox?

When did you noticed the change?

Were you doing anything or just idling?

How long was uTox open?

**Comment by vasisualiy** [comment]
Arch, uTox from git, uTox was open few minutes before it. It utilizes cpu when I conversate in it, audio call utilizes not 100%, but about 30-50%.

**Comment by vasisualiy** [comment]
Just installed a new git- version. The bug is still there.

**Comment by cebe** [comment]
I see similar behavior when I open video preview:

![bildschirmfoto von 2015-12-20 02 50 02](https://cloud.githubusercontent.com/assets/189796/11916045/9c32ac6e-a6c4-11e5-9113-9240d30d439a.png)

but that is rather normal, its not running at 100%. uTox and tox in general are quite cpu hungry because of all the threads running in the background even if there is nothing to do...

Implementation of the threads is based on while loops that sleep on a regular basis, e.g.: https://github.com/GrayHatter/uTox/blob/develop/video.c#L228

This causes a general background load on the CPU which looks like this on my system running a completely idle instance of utox:

![bildschirmfoto von 2015-12-20 02 57 40](https://cloud.githubusercontent.com/assets/189796/11916058/8c47afb0-a6c5-11e5-9a38-a8bdd0015a91.png)

To change this, the thread messaging implementation would have to be replaced with something more complex, e.g. mutex locking or stream select. Something like this maybe? http://cboard.cprogramming.com/linux-programming/116184-best-solution-inter-thread-communication.html#post864937

**Comment by vasisualiy** [comment]
>but that is rather normal, its not running at 100%. uTox and tox in general are quite cpu hungry because of all the threads running in the background even if there is nothing to do...

As far, as I can remember, in the problem did not exist 5 month ago, or so.

**Comment by GrayHatter** [comment]
@vasisualiy I was talking with @cebe last night, and we're pretty sure that it's the addition of the AV threads doing things when they don't need to be. I'm looking into optimization solutions now.

**Comment by vasisualiy** [comment]
Do I understand right, that this is a toxcore regression?

**Comment by GrayHatter** [comment]
no, It's the way utox threads to send audio and video

**Comment by cebe** [comment]
Pretty sure its the A/V threads, just checked with setting the sleep time to 50ms in both, just to verify:

![bildschirmfoto von 2015-12-21 02 12 24](https://cloud.githubusercontent.com/assets/189796/11921379/54b0e0c6-a788-11e5-85a8-050bfd347328.png)

**Comment by GrayHatter** [comment]
I'm rewriting uTox's a/v backend.
